#!sh

. "$XDG_CONFIG_HOME"/env/variables
export HISTSIZE=

. "$XDG_CONFIG_HOME"/sh/aliases
. "$XDG_CONFIG_HOME"/sh/fzf.sh

PS1='$(_ps1)'
_ps1 () {
    printf '\001\033]0;%s@%s:%s\007\002' \
        "$(id -un)"  "$(uname -n)"  "$(echo "$PWD" | sed "s,^$HOME,~,")"

    _ps1_os_name () {
        case "$(uname -s)" in
            Linux)
                [ -n "$WSL_DISTRO_NAME" ] && echo "$WSL_DISTRO_NAME" && return
                awk -F= '$1=="ID" { gsub(/"/, "", $2); print $2 }' /etc/*release
                ;;
            *) uname -s ;;
        esac
    }

    printf "\001\033[38;5;240m\002"
    printf '[%s]  [%s %d]  [ %s@%s  %s %s]' \
        "$(_ps1_os_name)" \
        "$(ps -p "$$" -o comm='' 2> /dev/null || echo "$0")" \
        "$(jobs | wc -l)" \
        "$(id -un)" \
        "$(uname -n)" \
        "$(echo "$PWD" | sed "s,^$HOME\(\/\|$\),~/,")" \
        "$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1 /')"
    printf "\001\033[0m\002"
    printf "\n"

    printf '\001\033[36m\002$\001\033[0m\002 '
}

sh << 'EOF' # permanent history entries
    HISTFILE="${HISTFILE:-$HOME/.sh_history}"
    touch "$HISTFILE"

    perm="$(mktemp)" || exit $?
    trap 'rm "$perm"' EXIT

    _append_to_perm_from () {
        file="$1"/sh/history.perm
        [ -s "$file" ] && cat "$file" >> "$perm";
    }
    _append_to_perm_from "$XDG_CONFIG_HOME"
    _append_to_perm_from "$HOSTDOTS"
    [ ! -s "$perm" ] && exit

    temp="$(mktemp)" || exit $?
    grep -v -F -x -f "$HISTFILE" "$perm" | cat - "$HISTFILE" > "$temp"

    if [ "$(wc -l < "$temp")" -gt "$(wc -l < "$HISTFILE")" ]; then
        mv "$temp" "$HISTFILE"
    else
        rm "$temp"
    fi
EOF

# shellcheck disable=SC1090,SC2154
trap '
    lg="$XDG_CONFIG_HOME"/sh/logout
    [ -f "$lg" ] && . "$lg"
' EXIT

[ -f "$HOSTDOTS"/sh/Shrc ] && . "$HOSTDOTS"/sh/shrc

[ -f "$HISTORY_DIR/oldpwd" ] && . "$HISTORY_DIR/oldpwd"
