#!sh

export HISTSIZE=
export HISTFILE="$HISTORY_DIR/$(basename "$SHELL")"

. "$XDG_CONFIG_HOME"/sh/aliases
. "$XDG_CONFIG_HOME"/sh/fzf.sh
. "$XDG_CONFIG_HOME"/sh/prompt.sh

sh << 'EOF' # permanent history entries
    HISTFILE="${HISTFILE:-$HOME/.sh_history}"
    touch "$HISTFILE"

    perm="$(mktemp)" || exit $?
    trap 'rm "$perm"' EXIT

    IFS=:
    for file in $${SH_HIST_PERM:-"$XDG_CONFIG_HOME"/sh/history.perm}; do
        [ -s "$file" ] && cat "$file" >> "$perm";
    done
    [ ! -s "$perm" ] && exit

    temp="$(mktemp)" || exit $?
    grep -v -F -x -f "$HISTFILE" "$perm" | cat - "$HISTFILE" > "$temp"

    if [ "$(wc -l < "$temp")" -gt "$(wc -l < "$HISTFILE")" ]; then
        mv "$temp" "$HISTFILE"
    else
        rm "$temp"
    fi
EOF

# shellcheck disable=SC1090,SC2154
trap '
    lg="$XDG_CONFIG_HOME"/sh/logout
    [ -f "$lg" ] && . "$lg"
' EXIT

[ -f "$HISTORY_DIR/oldpwd" ] && . "$HISTORY_DIR/oldpwd"
