xrandr --auto --dpi 96
setxbmap pl
xrdb -load $XDG_CONFIG_HOME/X11/Xresources
setxkbmap -option keypad:pointerkeys
echo "GPU $(glxinfo | grep -Fxq 'OpenGL vendor string: NVIDIA Corporation' && echo 'NVIDIA' || echo 'INTEL')" >> "$TMPFLAGS"
[ -x "$(command -v prime-offload)" ] && prime-offload

exec i3
