xrandr --auto --dpi 96
setxbmap pl
xset -b
xrdb -load $XDG_CONFIG_HOME/X11/Xresources
setxkbmap -option keypad:pointerkeys

if [ -x "$(command -v prime-offload)" ]; then
    echo "GPU $(glxinfo | grep -Fxq 'OpenGL vendor string: NVIDIA Corporation' && echo 'NVIDIA' || echo 'INTEL')" >> "$TMPFLAGS"
    prime-offload
fi

[ -x "$(command -v nvidia-settings)" ] && nvidia-settings --load-config-only

exec i3
