# BASHRC #

source "$ENV"

# Enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        source /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        source /etc/bash_completion
    fi
fi

shopt -s extglob

shopt -s histappend
export HISTCONTROL=ignoreboth:erasedups
