#!/usr/bin/env sh

SSH_CONFIG="-F ${XDG_CONFIG_HOME:-$HOME/.config}/ssh/config"
#SSH_ID="-i ${XDG_DATA_HOME:-$HOME/.local/share}/ssh/id_dsa"
SSH_KNOWN_HOSTS="-o UserKnownHostsFile=${XDG_DATA_HOME:-$HOME/.local/share}/ssh/known_hosts"

PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)

exec ssh $SSH_CONFIG $SSH_KNOWN_HOSTS "$@"
