#!/usr/bin/env sh

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
OPTIONS="-o IdentityFile=$SSH_ID -o UserKnownHostsFile=$XDG_DATA_HOME/ssh/known_hosts"

PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)

exec ssh-copy-id $OPTIONS "$@"
