#!/usr/bin/env sh

#~ applypatch-msg
#~ commit-msg
#~ fsmonitor-watchman
#~ p4-changelist
#~ p4-post-changelist
#~ p4-pre-submit
#~ p4-prepare-changelist
#~ post-applypatch
#~ post-checkout
#~ post-commit
#~ post-index-change
#~ post-merge
#~ post-receive
#~ post-rewrite
#~ post-update
#~ pre-applypatch
#~ pre-auto-gc
#~ pre-commit
#~ pre-merge-commit
#~ pre-push
#~ pre-rebase
#~ pre-receive
#~ prepare-commit-msg
#~ proc-receive
#~ push-to-checkout
#~ reference-transaction
#~ sendemail-validate
#~ update

#  # --------------------------------------------------
#  "$(dirname "$0")"/_run_local_hook "$(basename "$0")"

if [ -z "$1" ] && [ "$0" = "./_run_local_hook" ]; then
    find -L . -xtype l -samefile "$0" -delete  # GNU 'find' needed
    awk '/^#~/ {print $2}' "$0" | xargs -n1 ln -s "$0" 2> /dev/null
    exit
fi

hook="$(basename "$0")"
[ "$hook" = "_run_local_hook" ] && hook="$1" && shift
root="$(git rev-parse --show-toplevel)"
[ ! -x "$root"/.git/hooks/"$hook" ] && exit 0
"$root"/.git/hooks/"$hook" "$@"
