#!/bin/bash

#battery_time=$(upower -i $(upower -e | grep battery) | grep "time to empty")
#battery_time=$(echo ${battery_time//"time to empty:"/})

battery=$(acpi)
battery_percentage="$(echo $battery | awk -F [\ ,] '{print $5}')"
battery_state="$(echo "$battery" | awk -F [\ ,] '{print $3}')"

if [ $battery_state == "Discharging" ]; then
    battery_output="▼ $battery_percentage"
elif [ $battery_state == "Full" ]; then
    battery_output="● ($battery_percentage)"
elif [ $battery_state == "Unknown" ]; then
    battery_output="? $battery_percentage"
else
    battery_output="ϟ $battery_percentage"
fi

if [ ! -z $battery_time ]; then
    battery_output="$battery_output [$battery_time]"
fi

echo $battery_output
