#!/usr/bin/env sh

zero="$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')"

# shellcheck disable=SC2034
while read -r local_ref local_oid remote_ref remote_oid
do
    if [ "$local_oid" = "$zero" ]; then
        continue
    fi

    if [ -x "$(command -v git-fmt-diff)" ]; then
        out="$(git fmt-diff --color "$remote_oid" "$local_oid")"
        if [ -n "$out" ]; then
            echo "$out"

            printf "\n"
            printf 'Some of your changes differ from autoformatter output.\n'
            printf 'Are you sure you want to push without fixing them? [y/N] '

            exec < /dev/tty
            read -r yn
            case "$yn" in
                y|Y|yes|YES|Yes) exit 0 ;;
            esac

            exit 1
        fi
    fi
done
