#!sh

export GPG_TTY="$(tty)"

export HISTSIZE=
export HISTFILE="$XDG_STATE_HOME/$(basename -- "${0#-*}")_history"

. "$XDG_CONFIG_HOME"/sh/aliases
. "$XDG_CONFIG_HOME"/sh/prompt.sh

. "$XDG_CONFIG_HOME"/profile.d/30-variables.sh

k="key-bindings.$(basename "${BASH}${ZSH_NAME}")"
for d in /usr/share/fzf /usr/share/fzf/* /usr/share/*/fzf/*; do
    [ -f "$d/$k" ] && . "$d/$k" && break
done; unset k

sh << 'EOF' # permanent history entries
    HISTFILE="${HISTFILE:-$HOME/.sh_history}"
    touch "$HISTFILE"

    perm="$(mktemp)" || exit $?
    trap 'rm "$perm"' EXIT

    IFS=:
    for file in ${SH_HIST_SAV:-"$XDG_CONFIG_HOME"/sh/history.sav}; do
        [ -s "$file" ] && cat "$file" >> "$perm";
    done
    [ ! -s "$perm" ] && exit

    temp="$(mktemp)" || exit $?
    grep -v -F -x -f "$HISTFILE" "$perm" | cat - "$HISTFILE" > "$temp"

    if [ "$(wc -l < "$temp")" -gt "$(wc -l < "$HISTFILE")" ]; then
        mv "$temp" "$HISTFILE"
    else
        rm "$temp"
    fi
EOF

# shellcheck disable=SC1090,SC2154
trap '
    lg="$XDG_CONFIG_HOME"/sh/logout
    [ -f "$lg" ] && . "$lg"
' EXIT

[ -f "$XDG_STATE_HOME/OLDPWD" ] && . "$XDG_STATE_HOME/OLDPWD"
