#!sh

export GPG_TTY="$(tty)"

export HISTSIZE=
export HISTFILE="$XDG_STATE_HOME/$(basename -- "${0#-}")_history"

. "$XDG_CONFIG_HOME"/sh/aliases
. "$XDG_CONFIG_HOME"/sh/prompt.sh

k="key-bindings.$(basename "${BASH}${ZSH_NAME}")"
for d in /usr/share/fzf /usr/share/fzf/* /usr/share/*/fzf/*; do
    [ -f "$d/$k" ] && . "$d/$k" && break
done; unset k

sh << 'EOF' # prepend to HISTFILE
    [ -z "$HIST_FILES" ] && exit 0
    touch "${HISTFILE:=$HOME/.sh_history}"
    temp="${TMPDIR:-/tmp}/hist-$$"
    set -f && IFS=: && cat $HIST_FILES 2> /dev/null \
        | grep -v -F -x -f "$HISTFILE" \
        | cat - "$HISTFILE" > "$temp" \
        && mv "$temp" "$HISTFILE"
EOF

# shellcheck disable=SC1090,SC2154
trap '
    lg="$XDG_CONFIG_HOME"/sh/logout
    [ -f "$lg" ] && . "$lg"
' EXIT

[ -f "$XDG_STATE_HOME/OLDPWD" ] && . "$XDG_STATE_HOME/OLDPWD"
