#!/usr/bin/env sh

PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)
export REAL_HOME="$HOME"
HOME="${XDG_CONFIG_HOME:-$HOME/.config}/csh"

. $XDG_LIB_DIR/shell/wrapper_exec.sh
wrapper_exec "$@"
