#!/usr/bin/env sh

PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)
export REAL_HOME="$HOME"
HOME="${XDG_CONFIG_HOME:-$HOME/.config}/csh"

for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)"); do
    [ -x "$dir/$(basename $0)" ] && exec "$dir/$(basename $0)" "$@"
done
