#!/usr/bin/env sh

profile="${XDG_CONFIG_HOME:-$HOME/.config}/firefox"

for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)"); do
    [ -x "$dir/$(basename $0)" ] && firefox="$dir/$(basename $0)" && break
done

if [ ! -e "$profile" ]; then
    "$firefox" -CreateProfile "default $profile"
fi

for p in $@; do
    if [ "$p" = "--profile" ]; then
        exec $firefox "$@"
    fi
done

"$firefox" --profile "$profile" "$@" &

until [ -e "$HOME/.mozilla" ]; do sleep 1; done
rm -rf "$HOME/.mozilla/firefox/Crash Reports"
rmdir "$HOME/.mozilla/firefox/Pending Pings" "$HOME/".mozilla/* "$HOME/".mozilla
