#!/usr/bin/env sh

# Get real binary ("basename $0" instead of "firefox" for forks like Iceweasel)
for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)"); do
    [ -x "$dir/$(basename $0)" ] && firefox="$dir/$(basename $0)" && break
done

# Get default behaviour, if executed with "--profile" argument
for p in $@; do
    [ "$p" = "--profile" ] && exec $firefox "$@"
done

# Profile directory fits the best into XDG_DATA_HOME
profile="${XDG_DATA_HOME:-$HOME/.local/share}/firefox"

# Create profile if doesn't exist (you can change "default" to other name)
if [ ! -e "$profile" ]; then
    "$firefox" -CreateProfile "default $profile"
fi

# Launch browser and detach it from this script
"$firefox" --profile "$profile" "$@" &

# After ~/.mozilla is created, delete it
until [ -e "$HOME/.mozilla" ]; do sleep 1; done
rm -rf "$HOME/.mozilla/firefox/Crash Reports"
rmdir "$HOME/.mozilla/firefox/Pending Pings" "$HOME/".mozilla/* "$HOME/".mozilla
