#!/usr/bin/env sh

# if SHELL points also to XDG wrapper, then change it to actual executable
for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $SHELL)"); do
    [ -x "$dir/$(basename $SHELL)" ] && SHELL="$dir/$(basename $SHELL)" && break
done

. "$XDG_LIB_DIR/shell/progwrap.sh"
progwrap_exec -q -x "$XDG_CONFIG_HOME/gdb/init" "$@"
