#!/usr/bin/env sh

PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)
HOME="$XDG_FAKEHOME_DIR"
exec gzdoom -config $XDG_CONFIG_HOME/gzdoom/gzdoom.ini -savedir $XDG_CONFIG_HOME/gzdoom "$@"
