#!/usr/bin/env sh


XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

SSH_CONFIG="-F $XDG_CONFIG_HOME/ssh/config"
SSH_ID="$XDG_DATA_HOME/ssh/id_rsa"
OPTIONS="-o IdentityFile=$SSH_ID -o UserKnownHostsFile=$XDG_DATA_HOME/ssh/known_hosts"

PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)

exec $(basename $0) $SSH_CONFIG $OPTIONS "$@"
