#!/usr/bin/env sh

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

for a in $@; do
    [ "$a" = "-F" ] && CONFIG="UNSET"
    [ "$a" = "-i" ] && ID="UNSET"
    echo "$a"
done

[ -z "$CONFIG" ] && CONFIG="-F $XDG_CONFIG_HOME/ssh/config" || unset CONFIG
[ -z "$ID" ]     && ID="-i $XDG_DATA_HOME/ssh/id_rsa" || unset ID

OPTIONS="-o UserKnownHostsFile=$XDG_DATA_HOME/ssh/known_hosts"

for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)"); do
    if [ -x "$dir/$(basename $0)" ]; then
        exec "$dir/$(basename $0)" $CONFIG $ID $OPTIONS "$@"
    fi
done
