#!/usr/bin/env sh

for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)"); do
    if [ -x "$dir/$(basename $0)" ]; then
        exec "$dir/$(basename $0)" -f $XDG_CONFIG_HOME/tmux/tmux.conf "$@"
    fi
done
