#!/bin/bash

ssid="$(iw dev wlo1 info | grep "ssid" | awk '{print $2}')"
signal="$(awk 'NR==3 {print $4}''' /proc/net/wireless)"
signal=" [${signal:0:-1} dBm]"

if [ "$ssid" == "" ]; then
    ssid="[X]"
fi

echo "$ssid$signal"
