#!/usr/bin/env sh

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
[ -s "$XDG_DATA_HOME/ssh/id_rsa" ] && SSH_ID="-i $XDG_DATA_HOME/ssh/id_rsa"

PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)

exec ssh-copy-id $SSH_ID "$@"
