#!sh
# shellcheck disable=SC1090,SC2174,SC2155

. "$( # source <dotfiles>/env/variables
    t="$(file "$HOME"/.profile | awk '{ print $NF }')"

    [ -f "$t" ] && vars="$(dirname "$t")"/variables || vars=
    [ ! -f "$vars" ] && vars="$HOME/.local/config/env/variables"
    [ ! -f "$vars" ] && vars="$HOME/.local/config/env_variables"
    [ ! -f "$vars" ] && vars="$HOME/.config/env/variables"
    [ ! -f "$vars" ] && vars="$HOME/.config/env_variables"
    [ ! -f "$vars" ] && vars="/dev/null"

    echo "$vars"
)"

if [ ! -d "$XDG_RUNTIME_DIR" ]; then
    mkdir -p -m 0700 "$XDG_RUNTIME_DIR" # ought to be '/tmp/user-runtime'
fi
if [ "$(stat -c '%a' "$XDG_RUNTIME_DIR")" != 700 ]; then
    echo "\$XDG_RUNTIME_DIR: permissions problem with $XDG_RUNTIME_DIR:" >&2
    ls -ld "$XDG_RUNTIME_DIR" >&2
    export XDG_RUNTIME_DIR="$(mktemp -d "$TMPDIR/$USER"-runtime-XXXXXX)"
    echo "Set \$XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" >&2
fi


case "$-" in
    *i*)
        export SHELL="$(command -v launch_shell.sh)"
        [ -n "$SSH_CLIENT" ] && exec "$SHELL"
        ;;
esac
